### ISSUE TITLE
optimize.validate_model Issue

### ISSUE THREAD

**Issue by ale18032005** [chan-csu/ADToolbox#14]
When this method is call it give an error

```
Traceback (most recent call last):
  File "...", line 449, in <module>
    print(optimize.validate_model(model=model,data=training_data,plot=False))      
  File "...", line 569, in validate_model
    fig.add_trace(go.Scatter(x=out["model"].index,y=out["model"][variable],name=variable,mode="lines",line=dict(
AttributeError: 'NoneType' object has no attribute 'add_trace'
```

**Comment by ParsaGhadermazi** [comment]
This is fixed now!
